font:
  font-family: "'Shippori Mincho', serif"

aside:
  enable: false

subtitle:
  enable: true
  effect: false
  source: false
  sub:
    - Z会じゃないよ

menu:
  ホーム: /
  ドット会のブログ: /categories/blog
  ドット会の入試分析: /categories/analysis
  ドット会の問題: /categories/questions
  ドット会のデータ: /categories/data
  ドット会について: /about

category_ui: index

top_img: true
index_img: "#184D8F"
default_top_img: "#184D8F"

cover:
  default_cover:
    - https://lh3.googleusercontent.com/pw/ACtC-3dZ9dAffj0iAI8a4_fheZ6qXSYyZ7zqPJnwy_h1Mz6Jn_ENd0T6OU91YrQfCFeFQilOoQZlgWfnUbFDCzZENjhumdD7O8M0VvVwPWB8BTmSLmLskMPfAs7ET13rUr9UeKQ4HDbjJf-z984QVtRkFPTLEg=w781-h776-no?authuser=0
