font:
  global-font-size: 16px
  font-family: "'Shippori Mincho', serif"

aside:
  enable: true
  card_author:
    enable: true
    button:
      enable: false
  card_announcement:
    enable: false
  card_categories:
    enable: false
  card_tags:
    enable: false
  card_archives:
    enable: false
  card_webinfo:
    enable: false

social:
  fab fa-twitter: https://twitter.com/dotroidkai || Twitter

avatar:
  img: https://lh3.googleusercontent.com/pw/ACtC-3e553jDBZQqadx0wb9cbZDM3eXevMDHuaxwyKoOSaQgBP-nvbSwjl5Y0cs7uEOGsqyBijLIo4EQ12gEhdmGFuqXV6bZVBhBRfRxz8ittpsAp_b1GjBdQUx1PCRRYCc8jUWsg_I2yMKWJQCndyvkJhlnRw=w350-h349-no?authuser=0

subtitle:
  enable: true
  effect: false
  source: false
  sub:
    - Z会じゃないよ

menu:
  ホーム: /
  ドット会のブログ: /categories/blog
  ドット会の入試分析: /categories/analysis
  ドット会の問題: /categories/questions
  ドット会のデータ: /categories/data
  ドット会について: /about

category_ui: index

top_img: true
index_img: "#184D8F"
default_top_img: "#184D8F"

cover:
  default_cover:
    - https://lh3.googleusercontent.com/pw/ACtC-3dZ9dAffj0iAI8a4_fheZ6qXSYyZ7zqPJnwy_h1Mz6Jn_ENd0T6OU91YrQfCFeFQilOoQZlgWfnUbFDCzZENjhumdD7O8M0VvVwPWB8BTmSLmLskMPfAs7ET13rUr9UeKQ4HDbjJf-z984QVtRkFPTLEg=w781-h776-no?authuser=0

inject:
  head:
    - <!-- Global site tag (gtag.js) - Google Analytics -->
    - <script async src="https://www.googletagmanager.com/gtag/js?id=G-TP4NWXFXTW"></script>
    - <script>
    -   window.dataLayer = window.dataLayer || [];
    -   function gtag(){dataLayer.push(arguments);}
    -   gtag('js', new Date());
    -   gtag('config', 'G-TP4NWXFXTW');
    - </script>
    - <link rel="stylesheet" href="/custom_css.css" />

darkmode:
  enable: false

readmode: true

toc:
  enable: true
  number: false
  style_simple: true

theme_color:
  enable: true
  main: "#184D8F"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#184D8F"
  blockquote_background_color: "#184D8F"

favicon: /images/favicon.png
